version: "3.9"

services:
  # Our Postgres database
  db: # The service will be named db.
    image: postgres # The postgres image will be used
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: vityayka # POSTGRES_USER env var w/ value baloo
      POSTGRES_PASSWORD: azazaz1488
      POSTGRES_DB: zero # Database name
    ports: # Expose ports so that apps not running via docker-compose can connect to them.
      - 5432:5432 # format here is "port on our machine":"port on container"

  # Adminer provides a nice little web UI to connect to databases
  # adminer:
  #   image: adminer
  #   restart: always
  #   environment:
  #     ADMINER_DESIGN: dracula
  #   ports:
  #     - 3333:8080
