version: "3.9"

services:
  server:
     build:
       context: ./
       dockerfile: Dockerfile
     restart: always
     volumes:
       - ~/data/go-zero.pp.ua/images:/app/images
     depends_on:
       - db
  
  caddy:
    image: caddy
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./Caddyfile:/etc/caddy/Caddyfile

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ~/data/go-zero.pp.ua/psql:/var/lib/postgresql/data/pgdata